[workspace]
channels = ["conda-forge", "robostack-kilted"]
name = "ros_ws"
platforms = ["win-64", "linux-aarch64"]
version = "0.1.0"

# This runs automatically when the environment is activated
[target.linux.activation]
scripts = ["install/setup.bash"]

[target.win.activation]
scripts = ["install/setup.bat"]

[tasks]
build = "colcon build --symlink-install"
run_robot = "PYTHONPATH=/usr/lib/python3/dist-packages:$PYTHONPATH ros2 launch tank_bringup tank.launch.xml"
run_user_interface = "ros2 launch user_interface_bringup user_interface.launch.xml"

[dependencies]
ros-kilted-desktop = ">=0.12.0,<0.13"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-kilted-ament-cmake = ">=2.7.3,<3"
ros-kilted-ament-cmake-python = ">=2.7.3,<3"
opencv = ">=4.12.0,<5"
ros-kilted-rviz2 = ">=15.0.6,<16"
ros-kilted-rviz-common = ">=15.0.6,<16"
ros-kilted-rviz-default-plugins = ">=15.0.6,<16"
ros-kilted-image-transport-plugins = ">=5.1.1,<6"
numpy = "==1.26.4"
pygame = ">=2.6.1,<3"

[pypi-dependencies]
gpiozero = ">=2.0.1, <3"
