[workspace]
channels = ["conda-forge", "robostack-kilted"]
name = "ros_ws"
platforms = ["win-64", "linux-aarch64"]
version = "0.1.0"

# This runs automatically when the environment is activated
[activation]
scripts = ["install/setup.bash"]

[target.win.activation]
scripts = ["install/setup.bat"]

[tasks]
build = "colcon build --symlink-install"
run_cam_pub = "ros2 run camera camera_publisher"


[dependencies]
ros-kilted-desktop = ">=0.12.0,<0.13"
colcon-common-extensions = ">=0.3.0,<0.4"
ros-kilted-ament-cmake = ">=2.7.3,<3"
ros-kilted-ament-cmake-python = ">=2.7.3,<3"
opencv = ">=4.12.0,<5"
ros-kilted-rviz2 = ">=15.0.6,<16"
ros-kilted-rviz-common = ">=15.0.6,<16"
ros-kilted-rviz-default-plugins = ">=15.0.6,<16"
ros-kilted-image-transport-plugins = ">=5.1.1,<6"
numpy = "==1.26.4"

[pypi-dependencies]
gpiozero = ">=2.0.1, <3"
